# vim: set ts=2 et:
# TODO: Setup TravisCI for BEAGLES
# run xvfb with 32-bit color
# xvfb-run -s '-screen 0 1600x1200x24+32' command_goes_here

language: python

jobs:
  include:
    - os: osx
      services: xvfb
      language: generic
    - os: linux
      dist: bionic
      services: xvfb
      python: 3.6

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install python3-pip pyqt5-dev-tools libomp-dev build-essential; fi
install:
  - pyrcc5 -o libs/resources.py resources.qrc
  - python3 setup.py install
  - pip3 install codecov
script:
  - xvfb-run --auto-servernum make test
  - make coverage
  - codecov
  - exit 0
