# vim: set ts=2 et:
# TODO: Setup TravisCI for BEAGLES
# run xvfb with 32-bit color
# xvfb-run -s '-screen 0 1600x1200x24+32' command_goes_here

language: python

jobs:
  include:
    # Python 3 + QT5 - Build .app
    - os: osx
      language: generic
    - os: linux
      dist: bionic
      services: xvfb
      python: 3.6

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install python3-pip pyqt5-dev-tools libomp-dev libqt5x11extras5 xvfb; fi
install:
  - pip3 install codecov
  - pip3 install tox-travis
script:
  - xvfb-run --auto-servernum tox
  - make coverage
  - codecov
  - exit 0
