# vim: set ts=2 et:
# TODO: Setup TravisCI for SLGR-Suite
# run xvfb with 32-bit color
# xvfb-run -s '-screen 0 1600x1200x24+32' command_goes_here

language: python

jobs:
  include:
    # Python 3 + QT5 - Build .app
    - os: osx
      language: generic
    - os: linux
      python: 3.6

install:
  - pip3 install -r requirements/requirements-osx.txt
  - pyrcc5 -o libs/resources.py resources.qrc
  - python3 setup.py build_ext --inplace
script:
  - python3 -m unittest discover ./tests
  - exit 0
