# vim: set ts=2 et:
# TODO: Setup TravisCI for BEAGLES
# run xvfb with 32-bit color
# xvfb-run -s '-screen 0 1600x1200x24+32' command_goes_here

language: python

jobs:
  include:
    - os: osx
      services: xvfb
      language: generic
    - os: linux
      dist: bionic
      services: xvfb
      python: 3.6
    - os: linux
      dist: bionic
      services: xvfb
      python: 3.7
    - os: linux
      dist: bionic
      services: xvfb
      python: 3.8

before_install:
  - pip3 install PyQt5
  - pip3 install defusedxml>=0.6.0
  - pip3 install lxml>=4.2.4
  - pip3 install Cython==0.29.6
  - pip3 install opencv-contrib-python==4.0.0.21
  - pip3 install tensorflow>2.0.0b
  - pip3 numpy==1.16.2
  - pip3 traces==0.4.2
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install python3-pip pyqt5-dev-tools libomp-dev build-essential; fi
install:
  - pyrcc5 -o libs/resources.py resources.qrc
  - python3 setup.py build_ext --inplace
  - pip3 install codecov
script:
  - xvfb-run --auto-servernum make test
  - make coverage
  - codecov
  - exit 0