# vim: set ts=2 et:
# run xvfb with 32-bit color
# xvfb-run -s '-screen 0 1600x1200x24+32' command_goes_here

language: python

jobs:
  include:
    # Python 3 + QT5 - Build .app
    - os: osx
      language: generic
    - os: linux
      dist: bionic
      services: xvfb
      python: 3.7

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install python3-pip pyqt5-dev-tools libomp-dev libqt5x11extras5 xvfb; fi
install:
  - pip3 install tox-travis
  - pip3 install codecov
script:
  - pip3 install -r requirements.txt
  - make qt5
  - make cython
  - xvfb-run --auto-servernum make test
  - coverage run -m unittest discover tests
  - codecov
  - exit 0
