on: 
  pull_request:
    branches: master
    types: closed
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Tag Release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+
          prerelease_regex: ^v[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+[ab]+[[:digit:]]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
